name: Check Build

on: [pull_request]

jobs:
  build:

    strategy:
      matrix:
        php: ["7.4", "8.0"]

    runs-on: ubuntu-latest
    container:
      image: eventjet/checks-${{ matrix.php }}:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare environment
        run: |
          mkdir -p /root/.ssh
          ssh-keyscan -t rsa github.com >> /root/.ssh/known_hosts
          echo "COMPOSER_CACHE=$(composer config cache-dir)" >> $GITHUB_ENV

      - name: Composer Cache
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.COMPOSER_CACHE }}
            vendor
          key: ${{ runner.os }}-composer

      - name: Install dependencies
        run: |
          composer update --no-progress --no-interaction ${{ matrix.composer_args }} > /dev/null

      - name: PHPCS
        if: matrix.php != '8.0'
        run: |
          composer cs-check

      - name: Static analysis
        run: |
          composer check-deps
          composer phpstan -- --no-progress
          composer psalm

      - name: Tests
        run: |
          vendor/bin/phpunit --coverage-clover=coverage.xml --stop-on-failure
          composer run --timeout=0 infection

      - name: Monitor coverage
        if: github.event_name == 'pull_request'
        uses: slavcodev/coverage-monitor-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          clover_file: "coverage.xml"
          comment_context: PHP ${{ matrix.php }}
          threshold_alert: 100
          threshold_warning: 100
